# feeds/sp500.py
sp500_tickers = [
    "AAPL", "MSFT", "GOOGL", "GOOG", "AMZN", "NVDA", "META", "BRK-B", "TSLA", "LLY",
    "V", "JPM", "XOM", "JNJ", "UNH", "WMT", "MA", "PG", "AVGO", "HD",
    "ORCL", "CVX", "MRK", "COST", "ABBV", "PEP", "ADBE", "KO", "CRM", "BAC",
    "MCD", "CSCO", "ACN", "TMO", "PFE", "LIN", "ABT", "CMCSA", "NFLX", "DHR",
    "NEE", "AMD", "TXN", "NKE", "PM", "UPS", "MS", "HON", "INTC", "LOW",
    "GE", "RTX", "AMGN", "CAT", "IBM", "SBUX", "SCHW", "NOW", "SPGI", "GS",
    "ISRG", "DE", "PLD", "BKNG", "INTU", "ELV", "ADP", "LMT", "MDLZ", "TJX",
    "CI", "VRTX", "BLK", "GILD", "T", "SYK", "C", "COP", "AXP", "BA",
    "AMAT", "MMC", "CB", "ZTS", "ETN", "REGN", "ADI", "SO", "SLB", "DUK",
    "EOG", "PGR", "BDX", "AON", "BSX", "ITW", "MDT", "CSX", "NSC", "HUM",
    "CL", "SHW", "WM", "AMT", "MO", "NOC", "PYPL", "USB", "CVS", "COF",
    "PNC", "F", "GM", "EMR", "GD", "EL", "FDX", "TRV", "ICE", "MU",
    "TGT", "HCA", "ORLY", "MAR", "ROP", "MPC", "ADM", "MCK", "TEL", "ECL",
    "EXC", "CME", "APD", "WELL", "EQIX", "MSI", "MMM", "KLAC", "FCX", "PSX",
    "SYF", "TDG", "CTAS", "SNPS", "ADSK", "CMI", "PSA", "LRCX", "PCAR", "PH",
    "PAYX", "VLO", "APH", "NUE", "D", "FTNT", "KMB", "JCI", "INFO", "KMI",
    "AEP", "STZ", "AZO", "ROST", "MET", "AMP", "LHX", "CNC", "CTSH", "HIG",
    "DXCM", "MSCI", "OKE", "AJG", "FAST", "ODFL", "CDNS", "BK", "URI", "IQV",
    "VRSK", "CSGP", "WBA", "VRSN", "LYB", "EA", "ALL", "KEYS", "MCHP", "PRU",
    "HES", "PWR", "KHC", "BIIB", "EFX", "HAL", "MLM", "WY", "MTD", "BKR",
    "DVN", "KR", "AFL", "AME", "YUM", "EXR", "FANG", "CE", "MNST", "CPRT",
    "TROW", "CDW", "DHI", "BALL", "TT", "TRMB", "ESS", "IDXX", "LEN", "A",
    "WST", "GPN", "FIS", "IRM", "EXPD", "PEAK", "HPQ", "ROK", "RMD", "OTIS",
    "MTB", "ULTA", "SBAC", "BR", "ARE", "AVB", "GRMN", "AVY", "CCL", "CARR",
    "SRE", "VICI", "STE", "WEC", "HOLX", "PPG", "CAH", "WAB", "ANET", "MOH",
    "ETR", "HST", "DLR", "ILMN", "NVR", "RJF", "LYV", "TSCO", "CMS",
    "GWW", "KDP", "POOL", "FITB", "SWKS", "DG", "AWK", "CEG", "TTWO", "WTW",
    "DRI", "EXPE", "DAL", "CHTR", "EBAY", "FISV", "EQT", "UAL", "LKQ", "TER",
    "CFG", "AIG", "IFF", "WDC", "NTAP", "BXP", "GNRC", "CNP", "INVH", "PPL",
    "TXT", "HSY", "OXY", "HPE", "SYY", "FE", "MTCH", "XEL", "CTLT", "VTR",
    "LW", "LUV", "TFC", "WAT", "LVS", "OMC", "APA", "MAS", "ZBH", "PFG",
    "FSLR", "FMC", "DOV", "PKG", "SEDG", "WHR", "UHS", "SNA", "DPZ", "ROL",
    "BIO", "TECH", "NTRS", "PAYC", "GEN", "MGM", "HSIC", "WRK", "CTRA", "PTC",
    "FRT", "BRO", "CRL", "BF-B", "ALGN", "HWM", "PODD", "DFS", "CBOE", "MKTX",
    "CZR", "GLW", "NDAQ", "STX", "JBL", "ETSY", "BEN", "CHRW", "PEG", "LDOS",
    "XRAY", "REG", "STLD", "AKAM", "CDAY", "CINF", "JBHT", "ENPH", "IP", "AES",
    "ATO", "LLYVK", "LLYVA", "NI", "JKHY", "MRO", "EVRG", "AIZ", "WYNN",
    "MOS", "WRB", "TRGP", "NRG", "HBAN", "BAX", "FDS", "INCY", "UDR",
    "NWSA", "NWS", "PARA", "FOXA", "FOX", "DISCK", "DISCA", "TAP", "ZION", "PNW",
    "BBWI", "COO", "IVZ", "L", "EMN", "DVA", "RF", "SWK", "IPG", "FLT",
    "AMCR", "ALB", "VFC", "AXON", "GEHC", "KVUE", "SOLV", "VLTO", "TERADYNE", "PANW",
    "CDW", "QRVO", "DAY", "COR", "CTVA", "DOW", "OGN", "FRC", "SBNY", "ATVI",
    "TWTR", "DIS", "NEEPR", "BF.A", "BRK.A", "LEN.B", "UAA", "UA", "WRK", "TECH",
    "ALLE", "ANSS", "APA", "APTV", "BBY", "BLK", "BMY", "CA", "CBRE", "CF",
    "CHRW", "CMA", "CTL", "CXO", "DISCA", "DISCK", "DISH", "DLPH", "DPZ", "DPS",
    "DWDP", "DXC", "EIX", "ES", "ETFC", "EVHC", "FBHS", "FFIV", "FLIR", "FLR",
    "FTI", "GGP", "GT", "HAR", "HBI", "HCP", "HOG", "HRS", "INFO", "IR",
    "IRM", "JBHT", "JEF", "JNJ", "JNPR", "JWN", "K", "KHC", "KSS", "LB",
    "LEG", "LH", "LKQ", "LNT", "LUK", "LVLT", "MAC", "MAT", "MCO", "MDLZ",
    "MON", "NAVI", "NBL", "NFX", "NLSN", "NOV", "PCLN", "PFG", "PKI", "PRGO",
    "PVH", "PX", "PXD", "QCOM", "RHI", "RHT", "RIG", "RL", "RSG", "SCG",
    "SEE", "SIG", "SJM", "SLG", "SNI", "SRCL", "STI", "STT", "SYMC", "TIF",
    "TRIP", "TSN", "TWX", "VAR", "VIAB", "WAT", "WFM", "WLTW", "WMB", "WYN",
    "XL", "XLNX", "XPO", "XYL", "YHOO", "ZTS" # Adding more historical and some common ones to get closer
]
