name: audio test



permissions:
  contents: write

jobs:
  post-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python environment
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libjpeg-dev zlib1g-dev libfreetype6-dev
          python3 -m venv .venv

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          . .venv/bin/activate
          pip install --upgrade pip setuptools
          pip install --no-cache-dir \
            pytz requests python-dotenv "openai>=1.0.0" \
            google-cloud-texttospeech gtts

      - name: Write Google credentials to file
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > google-credentials.json

      - name: Verify Google Cloud credentials
        run: |
          . .venv/bin/activate
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/google-credentials.json"
          python -c "from google.cloud import texttospeech; client = texttospeech.TextToSpeechClient(); print('✅ Google Cloud authentication works')"

      - name: Generate blog voiceover (Wavenet)
        run: |
          . .venv/bin/activate
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/google-credentials.json"
          python generate_audio_from_blog.py

      - name: Upload blog audio to WordPress
        run: |
          . .venv/bin/activate
          python upload_audio_and_embed.py
        env:
          WP_USERNAME:     ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_SITE_URL:     ${{ secrets.WP_SITE_URL }}

      - name: Upload video to WordPress
        run: |
          . .venv/bin/activate
          python upload_video_to_wp.py
        env:
          WP_USERNAME:     ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_SITE_URL:     ${{ secrets.WP_SITE_URL }}
