name: Daily Form Monitoring

on:
  schedule:
    - cron: "0 14 * * *"  # Daily at 7 AM MST
  workflow_dispatch:

jobs:
  monitor-forms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Set CHROME options
        run: |
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run form monitor
        run: |
          python form_monitor.py

      - name: Send Slack Alert
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"📋 Daily Form Monitoring Report\n${{ steps.monitor.outputs.report }}"}' \  
          ${{ secrets.SLACK_WEBHOOK_URL }}
