name: Daily Form Monitoring

on:
  schedule:
    - cron: "0 14 * * *"  # Runs daily at 7:00 AM MST (adjust as needed)
  workflow_dispatch:       # Allows manual triggering from GitHub

jobs:
  monitor-forms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Set CHROME options
        run: |
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run form monitor
        run: |
          python form_monitor.py
