name: Test Edit Video Only

on:
  workflow_dispatch:  # manually trigger from GitHub UI

jobs:
  test-edit-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python3 -m venv .venv

      - name: Install Python dependencies
        run: |
          .venv/bin/pip install --upgrade pip setuptools
          .venv/bin/pip install --no-cache-dir \
            pillow==9.5.0 moviepy==1.0.3 imageio==2.31.1 imageio-ffmpeg==0.4.8 \
            ffmpeg-python

      - name: Run edit_and_merge_video.py
        run: .venv/bin/python edit_and_merge_video.py

      - name: Commit and push generated video
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add video_output.mp4
          git commit -m "Save test generated video_output.mp4 [skip ci]" || echo "No video changes to commit"
          git push
