name: Upload Video to YouTube Shorts

on:
  workflow_dispatch:  # Trigger manually from GitHub Actions UI

permissions:
  contents: read  # Only need to read repo files

jobs:
  upload-to-youtube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        run: |
          sudo apt-get update
          python3 -m venv .venv

      - name: Install YouTube uploader dependencies
        run: |
          .venv/bin/pip install --upgrade pip setuptools
          .venv/bin/pip install google-auth google-auth-oauthlib google-api-python-client python-dotenv

      - name: Restore YouTube token
        run: echo "$YOUTUBE_TOKEN_B64" | base64 -d > youtube_token.pkl
        env:
          YOUTUBE_TOKEN_B64: ${{ secrets.YOUTUBE_TOKEN_NEW }}

      - name: Upload video to YouTube Shorts
        run: .venv/bin/python upload_to_youtube.py
