name: test

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: write

jobs:
  post-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python environment
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libjpeg-dev zlib1g-dev libfreetype6-dev
          python3 -m venv .venv

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/generate_video_heygen.py', '**/edit_and_merge_video.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          .venv/bin/pip install --upgrade pip setuptools
          .venv/bin/pip install --no-cache-dir \
            pytz requests python-dotenv openai>=1.0.0 \
            ffmpeg-python natsort pillow==9.5.0 imageio==2.31.1 imageio-ffmpeg==0.4.8 \
            moviepy==1.0.3 yfinance feedparser \
            google-cloud-texttospeech gtts

      - name: Fetch market data and save snapshot
        run: .venv/bin/python market_snapshot_fetcher.py

      - name: Run blog and summary generator
        run: .venv/bin/python final.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WP_USERNAME:     ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_SITE_URL:     ${{ secrets.WP_SITE_URL }}

      - name: Write Google credentials to file
        run: echo "$GOOGLE_CREDENTIALS_JSON" > google-credentials.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Verify Google Cloud credentials
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/google-credentials.json"
          .venv/bin/python -c "from google.cloud import texttospeech; client = texttospeech.TextToSpeechClient(); print('Google Cloud auth works')"

      - name: Generate blog voiceover
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/google-credentials.json"
          .venv/bin/python generate_audio_from_blog.py

      - name: Generate 20s video narration
        run: .venv/bin/python generate_video_prompt.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate avatar video
        run: .venv/bin/python generate_video_heygen.py
        env:
          HEYGEN_API_KEY: ${{ secrets.HEYGEN_API1 }}

      - name: Save generated avatar video immediately
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add avatar_video.mp4
          git commit -m "Save generated avatar_video.mp4 [skip ci]" || echo "No avatar video changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push

      - name: Upload blog audio to WordPress
        run: .venv/bin/python upload_audio_and_embed.py
        env:
          WP_USERNAME:     ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_SITE_URL:     ${{ secrets.WP_SITE_URL }}

      - name: Commit history logs
        if: success()
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add blog_history.txt market_snapshot_log.jsonl
          git commit -m "Update history logs [skip ci]" || echo "No history changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
