name: Upload YouTube Shorts

on:
  workflow_dispatch:  # Manual trigger (can also use push, schedule, etc.)

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client

      - name: Prepare YouTube OAuth credentials
        run: |
          echo '${{ secrets.YT_CREDENTIALS_JSON }}' > credentials.json
          echo '${{ secrets.YT_TOKEN_JSON }}' > token.json

      - name: Upload video to YouTube Shorts
        run: python upload_to_youtube.py
