name: Upload YouTube Shorts

on:
  workflow_dispatch:  # Manual trigger (can also use push, schedule, etc.)

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-api-python-client

    - name: Prepare YouTube OAuth credentials
      run: |
        echo "${{ secrets.YT_CREDENTIALS_BASE64 }}" | base64 --decode > credentials.json
        echo "${{ secrets.YT_TOKEN_BASE64 }}" | base64 --decode > token.json

    - name: Upload video to YouTube Shorts
      run: python upload_to_youtube.py
